### ISSUE TITLE
DevApp demo not working in Firefox (customElements / Web Components)

### ISSUE THREAD

**Issue by NinjaDero** [dsuryd/dotNetify-Elements#1]
dotNetify-Elements: efc87e29820dce79290d3a98f21e5aa6c430403f
dotnet Core: 2.1.300
Firefox: 60.0.1 (64bit)
npm: 6.1.0
OS: Ubuntu 18.04 LTS

A freshly cloned project, npm packages installed, built and started, does not seem to work in Firefox.
![screenshot_firefox_console](https://user-images.githubusercontent.com/4938127/41284566-f323bd44-6e39-11e8-8363-09d752e725ac.png)

Anything I can do about that, or are we waiting for Mozilla to finish their Web Components? :(

**Comment by dsuryd** [comment]
Polyfill for custom components will make it right as rain 😊

Browser compatibility is in the to-do list.

**Comment by dsuryd** [comment]
Latest check-in should work with Firefox, now that the web component example is booted out.

**Comment by NinjaDero** [comment]
It does, thanks. :+1:
