### ISSUE TITLE
Can definition of an onclick in a button not override default behaviour?

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#10]
The button with id=New does an action defined in the server viewmoder:
```
            AddProperty<object>("New")
                .Subscribe(_ => ClearForm());
```
Problem is if I define for that button a custom function for onclick then the action in the server is not called, only is called the one in the client. How can I make both are executed?
```
class FamilyForm extends React.Component {

    state = { updateEdit: false, newEdit: false };

    toggleUpdateEdit = _ => this.setState({ updateEdit: !this.state.updateEdit });
    toggleNewEdit = _ => {
        this.setState({ newEdit: !this.state.newEdit });
    }

    render() {
        const { updateEdit, newEdit } = this.state;
        const edit = () => updateEdit || newEdit; 
        return (
            <VMContext vm="FamilyVM">
                        {!edit() && <TextField label="Go to" />}
                        <Button label="New" id="New" onClick={this.toggleNewEdit} show={!edit()} enable={!edit()} />
             </VMContext>
```

**Comment by dsuryd** [comment]
If the `onClick` handler returns a value, that value will be dispatched to the server.  In your case, simply have the `toggleNewEdit` returns null.

**Comment by jersiovic** [comment]
I have changed `toggleNewEdit` to this: `toggleNewEdit = _ => { this.setState({ newEdit: !this.state.newEdit }); return new object; }` without no luck.
Also tried simply with: `toggleNewEdit = _ => new object;` but it didnd't work.

Changing returned type to bool didn't worked:
`AddProperty<object>("New").Subscribe(_ => ClearForm());`
`toggleNewEdit = _ => { this.setState({ newEdit: !this.state.newEdit }); return true; }`
or `toggleNewEdit = _ => true;` 

Only way server is called is when I remove onclick handler

**Comment by dsuryd** [comment]
Return null if prop type is ‘object’.  If you return boolean true, the prop
type has to match, change it to bool.

**Comment by jersiovic** [comment]
thank you, ti works
