### ISSUE TITLE
Panel right disables default vertical

### ISSUE THREAD

**Issue by larsbuch** [dsuryd/dotNetify-Elements#11]
In the Panel example selecting right disables the default vertical. I would have expected the boxes to be on the right vertically. It is like right expect horizontal to be active.

![panel no right](https://user-images.githubusercontent.com/11513991/45925813-dcd90600-bf1c-11e8-8cd6-ffc8940ed3c1.png)
![panel right](https://user-images.githubusercontent.com/11513991/45925814-df3b6000-bf1c-11e8-9ed7-9858ef725385.png)

**Comment by dsuryd** [comment]
You're right, it's not consistent.  Fixed this.
