### ISSUE TITLE
A Modal with onSubmit handler doesn't allow to use onChange like Form element

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#14]
Hi,
I have a modal element with an onSubmit handler. It makes client doesn't dispatch to server fields till submit is called. However I need some of the fields (a textfield and a dropdownlist) within this modal to be updated on the server when the dropdownlist selection changes or when a textfield receives a new keystroke.
I have tried to use onChanged event, but I've seen it is only available for forms not for modals. 
Can be this event added to modal? Would I need sth else to dispatch the value of those fields to the server?

Many thanks for your quick answers

**Comment by dsuryd** [comment]
If you add `.WithServerValidation()` to the property in the view model, any update on that property value will go immediately to the server, which you can then handle with pushing data back to the client.

**Comment by jersiovic** [comment]
It works :)
