### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by larsbuch** [dsuryd/dotNetify-Elements#15]
It would be nice to have TypeScript support.

I have tried to generate via dts-gen

`dts-gen -m dotnetify-elements`

but I unfortunately get a ReferenceError: window is not defined

**Comment by larsbuch** [comment]
I will try another generation technique to get a starting point for the .d.ts (mis)using the typescript compiler. I will let you know how the experiment went.

**Comment by larsbuch** [comment]
Not an issue for me any longer. I like the idea of the library.
I have stopped testing because of missing TypeScript support and that I need to rewrite  validation to work both on server and client to limit validation mismatch or forgotten validation.
I will submit my suggested rewrite so but not right now.

**Comment by dsuryd** [comment]
Thank you for the taking the time to test and submit honest feedbacks.  They will definitely be considered for future improvements of this library.

**Comment by dsuryd** [comment]
Closing this as I don't have plan to use Typescript for this library in the near future.  And as this is open-source, somebody who needs it can help out with the process.
