### ISSUE TITLE
Property validation

### ISSUE THREAD

**Issue by larsbuch** [dsuryd/dotNetify-Elements#16]
The validation is only for the client side (so I need to write same validation in WithServerValidation) or is the validation also done on the server when receiving the data from the client?
Client validation is mainly the usability validation but the server validation is the data validation you can trust. I hope it is data validation you aim for but documentation is not clear. I will test it tomorrow.

**Comment by dsuryd** [comment]
It’s only client side.   If you need to, you could revalidate the form data when it’s aggregated and received by the submit handler.

**Comment by dsuryd** [comment]
Closing this issue as client-side validation is sufficient for this library.  I am taking the position that server-side validation should be done by domain models, not view models.
