### ISSUE TITLE
Support for DOCTYPE html

### ISSUE THREAD

**Issue by jwyackel** [dsuryd/dotNetify-Elements#17]
Spent the most part of today trying to figure out why the new Layout component 'Main' wasn't filling whole screen  in my new project as it does in the SPA template.

Turns out the 'dotnet new react' template generates an index.html with DOCTYPE html at the top.  The SPA template does not have a DOCTYPE set.

I can leave the doctype out for now but wanted to see if this was on the to do list for future versions.

**Comment by dsuryd** [comment]
Good catch! Fortunately, easy to fix:
```html
<!DOCTYPE html>
<html>
    <head>
       <style>html, body, #App { height: 100%; }</style>
```

**Comment by jwyackel** [comment]
Thank you very much.
