### ISSUE TITLE
OnSubmit on a Modal element doesn't work on some circumstances

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#18]
Take a look to this sample:
```
import React from 'react';
import dotnetify from 'dotnetify';
import { withTheme, Modal, TextAreaField, VMContext, Form, Element,DataGrid, DropdownList, Alert, Panel, TextField, Button  } from 'dotnetify-elements';

dotnetify.debug = true
class SearchDialog extends React.Component {
    handleClose = _ => this.props.onClose();
    handleSubmit = item => { this.props.onSubmit(item); return false; };
    
    render() {
        return (
            <VMContext vm="SearchDialogVM"  >
                <Modal header="Search Dialog" large open={() => open} onSubmit={this.handleSubmit} >
                    <Panel horizontal>
                        <TextField label="Value" id="Value" />
                        <TextField id="SelectedResult" show={true} />
                    </Panel>
                    <footer>
                        <Panel right>
                            <Button label="Cancel" cancel secondary onClick={this.handleClose} enable={true} />
                            <Button id="Submit" label="Submit" submit onClick={this.handleClose} enable={true} />
                        </Panel>
                    </footer>
                </Modal>
            </VMContext>
        )
    }
}
export default withTheme(SearchDialog);
```
```
using System;
using DotNetify;
using DotNetify.Elements;

namespace PCCOM.Distrib.SPA.ProductsManagement.SPAViewModel
{
    
    public class SearchDialogVM : BaseVM
    {
        public SearchDialogVM() : base()
        {
            AddProperty("Value", "");
            AddProperty("SelectedResult", "0");
        }
    }
}
```
Previous example works properly and handleSubmit  is called.
If I replace this `AddProperty("Value", "")` per this: `AddProperty("Value", "0");` or per this `AddProperty("Value", "0").WithServerValidation(input => true, "");` it also works properly.
However if I replace it per this `AddProperty("Value", "").WithServerValidation(input => true, "");` the handleSubmit  is not called. 
Why?

Thank you

**Comment by dsuryd** [comment]
I could not reproduce your issue.   Here's the test code:
```jsx
import React from "react";
import dotnetify from "dotnetify";
import { withTheme, Modal, VMContext, Panel, TextField, Button } from "dotnetify-elements";

dotnetify.debug = true;

class SearchDialog extends React.Component {
  handleClose = _ => this.props.onClose();
  handleSubmit = item => {
    console.log("HandleSubmit:", item);
    //this.props.onSubmit(item);
    return false;
  };

  render() {
    return (
      <VMContext vm="SearchDialogVM">
        <Modal header="Search Dialog" large open={() => open} onSubmit={this.handleSubmit}>
          <Panel horizontal>
            <TextField label="Value" id="Value" />
            <TextField label="&nbsp;" id="SelectedResult" show={true} />
          </Panel>
          <footer>
            <Panel right>
              <Button label="Cancel" cancel secondary onClick={this.handleClose} enable={true} />
              <Button id="Submit" label="Submit" submit onClick={this.handleClose} enable={true} />
            </Panel>
          </footer>
        </Modal>
      </VMContext>
    );
  }
}
export default withTheme(SearchDialog);
```
```csharp
using System;
using DotNetify;
using DotNetify.Elements;

namespace spa_template
{
    public class SearchDialogVM : BaseVM
    {
        public SearchDialogVM() : base()
        {
            AddProperty("Value", "").WithServerValidation(input => true, "");
            AddProperty("SelectedResult", "0");
        }
    }
}
```
The output:
![image](https://user-images.githubusercontent.com/14990482/46384510-ee04de00-c6a5-11e8-902c-426a6493a4e5.png)


As you can see, the `console.log` in `handleSubmit` was hit.

**Comment by jersiovic** [comment]
Yes you are right. Trying to reproduce the problem I found it happens if in the viewmodel you have also a property for Value defined:
```
public string Value
{
      get => Get<string>();
      set => Set(value);
}
```

**Comment by jersiovic** [comment]
If I declare that property private it works properly

**Comment by jersiovic** [comment]
Problem of declaring it private is other problem arises in  more complex modal form where in the server side you assing a value to Value property: Since that moment any change to Value property at client side is ignored. Previous changes in client side of Value property are properly reflected on server side, it only starts to don't update on server  those changes which happened on client side after server sets a value to Value private property.

**Comment by dsuryd** [comment]
I'm not sure why you would put two properties of the same name - this will lead to unpredictable behavior - I'll probably put an error check in the future to prevent this from happening.

**Comment by jersiovic** [comment]
I though both styles of declarations were referencing the same property.
I use dynamic declaration style to be able of using `.WithServerValidation(input => true, "");`
but also the static style cause I wanted to have a property to work with it within the VM assigning and getting it values without haveing to deal with ReactiveProperty wrapper.

**Comment by jersiovic** [comment]
So, I've replaced the static one per:
```
...
_value =  AddProperty<string>(nameof(Value), "")
...
private ReactiveProperty<string> _value;
private string Value
        {
            get => _value.Value as string;
            set => _value.Value = value;
        }
```

**Comment by jersiovic** [comment]
Is there any other posibility for getting what I want?

**Comment by dsuryd** [comment]
You're basically creating a non-reactive property out of a reactive one, which runs counter to this library's principle.  But if you insist, you must give them different names.

**Comment by jersiovic** [comment]
I see what you mean. 
The point is library provides two paths to work: one using reactive properties and another without them. In my case I was interested on using the non reactive path, problem is I don't know how to configure things for non reactive properties to set Options for DropdownLists elements, Columns for grid elements, of force server validation. Can this be set through annotations or in the view code? Or as I suspect the non reactive path is limited?

**Comment by dsuryd** [comment]
The library's foundation is reactive programming; there's no plan - at least in the near future - to support other alternative.
