### ISSUE TITLE
Cross Browser support

### ISSUE THREAD

**Issue by jwyackel** [dsuryd/dotNetify-Elements#19]
Using the SPA template as an example,
FireFox - does not load the dotNetify logo.
Edge - does not load the dotNetify logo.  Can't enter anything into the login screen.

No errors in the console to indicate what's wrong.

Any ideas?

**Comment by dsuryd** [comment]
The TextField has problem with Edge due to the way browser renders the elements (the input element is laid under an empty div, workaround  is to use Tab to set the focus).  This will be fixed in the next publish.

The logo is css styling issue.  Replace the code in `Login.js` with this:
```jsx
export const Logo = styled.div`
  display: flex;
  align-items: center;
  margin-left: 1rem;
  background-image: url(http://dotnetify.net/content/images/dotnetify-logo.png);
  background-size: 100% 100%;
  width: 200px;
  height: 39px;
`;
```

**Comment by jwyackel** [comment]
Thank you, that is helpful.
