### ISSUE TITLE
Logo Proposal for dotNetify

### ISSUE THREAD

**Issue by area55git** [dsuryd/dotNetify-Elements#2]
Hi, I'm a graphic designer and I like to collaborate with open source projects. Do you know that the graphic image of a project is very important? thinking about it I would like to design a logo for your Project dotNetify.

I will be pleased to collaborate with you.

**Comment by dsuryd** [comment]
Thank's, sure, let me know you have in mind!  I'm really curious how you would evolve that humble little green dot into something nicer and more [Reactive ](http://reactivex.io/):)     

This is the current logo at twitter:
![image](https://user-images.githubusercontent.com/14990482/41310052-3c879424-6e35-11e8-9cc0-ae18049dd237.png)

and with text:
![image](https://user-images.githubusercontent.com/14990482/41310130-7ae31aae-6e35-11e8-87f4-c85239ae984d.png)

**Comment by area55git** [comment]
Perfect, I'm going to review your twitter account to get an idea and in a couple of days I sent you some proposals

**Comment by area55git** [comment]
Hi @dsuryd I think that this is how your logo should evolve

[![LOGO_PROPOSAL_FOR_do_Netify.jpg](https://s33.postimg.cc/ueqy8ntrj/LOGO_PROPOSAL_FOR_do_Netify.jpg)](https://postimg.cc/image/5y8se6t0r/)

I hope you like my proposal

**Comment by area55git** [comment]
Remember that this is a sketch, you can make any changes or suggestions.

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_do_Netify_2.jpg](https://s33.postimg.cc/baxmsqwhb/LOGO_PROPOSAL_FOR_do_Netify_2.jpg)](https://postimg.cc/image/npket2nzf/)

**Comment by dsuryd** [comment]
Wow, that's pretty cool!  I love that it's a composite of symbols that each has its own meaning.  Thank you!  My feedback is that the logo with the color can use a little more contrast on the white background.  
And do you have recommendation of a complementary color for the twitter background?

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_do_Netify_2.jpg](https://s33.postimg.cc/hjo26gpkv/LOGO_PROPOSAL_FOR_do_Netify_2.jpg)](https://postimg.cc/image/ectimu54r/)

I like it, do you?

**Comment by dsuryd** [comment]
Looks good!

**Comment by area55git** [comment]
The logo can also be in 2 colors

[![LOGO_PROPOSAL_FOR_do_Netify_3.jpg](https://s33.postimg.cc/qfyuaddm7/LOGO_PROPOSAL_FOR_do_Netify_3.jpg)](https://postimg.cc/image/yy8aepk4r/)

**Comment by area55git** [comment]
[![LOGO_PROPOSAL_FOR_do_Netify_4.jpg](https://s33.postimg.cc/hky008enj/LOGO_PROPOSAL_FOR_do_Netify_4.jpg)](https://postimg.cc/image/ahq4km97v/)

**Comment by dsuryd** [comment]
I like it with 2 colors.  Blue make it too similar with the globe, I'll go with the top grey one.

![image](https://user-images.githubusercontent.com/14990482/41384958-b41a2e0e-6f2d-11e8-9128-e285e6c96f75.png)

**Comment by area55git** [comment]
Perfect, I will prepare the final art in various formats (SVG, PNG, Etc.) and send them by G-Drive, I will make a PR to place the logo in the Readme folder

**Comment by area55git** [comment]
# [FILE DOWNLOAD](https://drive.google.com/open?id=1_TZs7NpDoAcHT11-idoTZSoN4l1hxh5o)

[![DERECHOS.jpg](https://s33.postimg.cc/phx6g77hr/DERECHOS.jpg)](https://postimg.cc/image/3vi5z68x7/)
This work is licensed under a [Creative Commons Attribution 4.0 International License.](https://creativecommons.org/licenses/by/4.0/)

**Comment by area55git** [comment]
Hi @dsuryd , I already made a PR

**Comment by dsuryd** [comment]
I see you forked the project, but you didn't do any PR.

**Comment by area55git** [comment]
![image](https://user-images.githubusercontent.com/38330420/41428262-7b45522a-6fd7-11e8-9849-641dd06f2c55.png)

**Comment by area55git** [comment]
![image](https://user-images.githubusercontent.com/38330420/41428346-cd1780a0-6fd7-11e8-97b7-f1f3df9e1108.png)

**Comment by dsuryd** [comment]
Click on that "Create pull request".

**Comment by area55git** [comment]
Thank you for allowing me to contribute to your project, enjoy it

**Comment by dsuryd** [comment]
Thank you so much!  How would you like to be credited?  Would you like to have your name and link to your portfolio mentioned in the readme?

**Comment by area55git** [comment]
I would love to!

**Comment by dsuryd** [comment]
Give me all that info, I'll put it up.

**Comment by area55git** [comment]
Just put my github account, that's enough.

**Comment by area55git** [comment]
@dsuryd In the G-Drive link I uploaded 2 images in JPG and a line separator in SVG

## Image 1
[![dot_Netify_1.jpg](https://s33.postimg.cc/cbq3zpi73/dot_Netify_1.jpg)](https://postimg.cc/image/wj3js0fob/)

## Image 2
[![dot_Netify_2.jpg](https://s33.postimg.cc/5l9mqaxm7/dot_Netify_2.jpg)](https://postimg.cc/image/u1rskrycr/)

## Separator
[![Separador_dot_Netify.png](https://s33.postimg.cc/g83fvt5sf/Separador_dot_Netify.png)](https://postimg.cc/image/szhm2bfkb/)

**Comment by dsuryd** [comment]
Looks really nice!  What font type are you using, btw ?

**Comment by area55git** [comment]
[Microsoft New Tai Lue](https://fontzone.net/font-details/microsoft-new-tai-lue)

**Comment by dsuryd** [comment]
Would you mind updating the colors?  They don't look contrast enough on the white background.  I found these colors work: green #92d050  (this is the original logo color), and gray #7F7F7F.

**Comment by area55git** [comment]
ok, later I update and I confirm you

**Comment by area55git** [comment]
Done, it's updated, check.

**Comment by dsuryd** [comment]
Thank you!
