### ISSUE TITLE
React 16.5 breaks DataGrid component

### ISSUE THREAD

**Issue by jwyackel** [dsuryd/dotNetify-Elements#20]
Updating past react 16.4.2 breaks the DataGrid component.

![image](https://user-images.githubusercontent.com/38192188/46552454-f4f34280-c897-11e8-8673-fdd80121b180.png)

My project was at 16.5.2 and I started to put in a DataGrid and had these errors.  I checked the sample template and it was using 16.3.2 so I started there and increased versions.  

I'll stay at 16.4.2 for now.  I don't have a requirement for later versions, I was using the latest since I am starting a new project.

**Comment by dsuryd** [comment]
Updated to react 16.6.0, didn't see any error on all DataGrid examples.
