### ISSUE TITLE
Is it possible to change option of a dropdownlist after initializacion?

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#21]
This is related with this other one issue https://github.com/dsuryd/dotNetify/issues/125 
I need to pass an argument to a viewmodel and depending on that argument fulfill controls on that modal.
It is not possible to pass that argument through contructor, so, I use a text element in the modal to pass that value.
Problem is when this text element is changed I cannot provide new DropdownListAttribute based on the new value passed to  an existing DropDownList within that modal.
Is there a way of doing that?

**Comment by dsuryd** [comment]
Yes:
```jsx
<VMContext vm="SearchDialogVM" options={{ vmArg: { Value: 'initial value' } }}>
   ...
   <TextField id="MyTextBox" />
```
```csharp
public SearchDialogVM() : base()
{
    AddProperty<string>("Value").Subscribe(value => {
        AddProperty<string>("MyTextBox", value)
            .WithAttribute(new TextFieldAttribute { Label = "Value" });
    });
   ...
```

**Comment by jersiovic** [comment]
Yeah it worked, thank you
