### ISSUE TITLE
Is source code available for the React components of DotNetify-Elements?

### ISSUE THREAD

**Issue by jwyackel** [dsuryd/dotNetify-Elements#24]
Have you made the javascript/react code available on GitHub?  I only see the server-side code.

Could I see for example, the React code for the NavMenu?

I'd like to make a NavMenu that collapses but shows the icons rather than hiding the whole component.
I'd like to see how you made your control as an example.

Thank you,

Jeremy

**Comment by dsuryd** [comment]
Everything's here: https://github.com/dsuryd/dotNetify-Elements/tree/master/DevApp/src/dotnetify-elements

**Comment by jwyackel** [comment]
Sorry about that, I missed that directory!

Thanks.
