### ISSUE TITLE
Allow Datagrid to return a composite key or the whole row as Selected Result

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#25]
Currently it only allows to choose a single RowKey and return its value when a row is selected. But I would like to have the possibility of setting a composite key and get returned its value.
Another alternative would be to get all the selected row.

**Comment by dsuryd** [comment]
What is the use case where the key isn’t enough?  The entire data can be read on the back-end given the key.

**Comment by jersiovic** [comment]
We are working on migrating a legacy code app to react+ dotnetify app. Both apps will coexist using same db till the new one is finished. The db has tables with composite keys and no alternate keys of one field. 
To add a incremental key or sth like that it is not an option cause legacy app need to continue working with same db and it uses foreign keys everywhere based on the composite key.

**Comment by dsuryd** [comment]
The view layer doesn't need to be dictated by the database constraint.  It would be simpler if your view model have presentation data model from the db table, which has additional property that dynamically encodes a unique key from the composite key (e.g. by string concatenation).    On selected grid row event, the key can be decoded back on the server to locate the associated db table row.

**Comment by jersiovic** [comment]
:+1:
