### ISSUE TITLE
How to add a column with a button in GridData

### ISSUE THREAD

**Issue by haifzhan** [dsuryd/dotNetify-Elements#26]
Hi, is it possible to add a column with a button for DataGrid?
I read the documentation but didn't find how to customize it.

![screenshot 2018-10-31 15 27 18](https://user-images.githubusercontent.com/1904812/47819944-9350b780-dd21-11e8-8f2a-91ddfea069be.png)

**Comment by dsuryd** [comment]
The `GridColumn` element provides a `formatter` property that you can use to customize the content of the column.  In the `DataGrid` documentation example, you can see it being used to format the date column.   This property accepts a proper React component, so you can render practically anything.
