### ISSUE TITLE
NavDrawerButton doesn't seem to show nor work

### ISSUE THREAD

**Issue by jsaez868** [dsuryd/dotNetify-Elements#27]
Using the elements template, the  NavDrawerButton doesn't seem to show nor work in hiding/showing the Nav section. Am I missing something?

**Comment by dsuryd** [comment]
I ran the template; it works as expected:
![navdrawerbutton](https://user-images.githubusercontent.com/14990482/47870560-bd79a680-de01-11e8-9e1e-10e211dec89d.gif)

The button shows up when the screen size is less than 768px.

**Comment by jsaez868** [comment]
Thanks.
