### ISSUE TITLE
Is it possible to use this library with Material UI Layout/Styling?

### ISSUE THREAD

**Issue by tjackadams** [dsuryd/dotNetify-Elements#30]
Hello,

I'm currently using https://material-ui.com/ for my layout/styling needs, most of the styles are defined at the top level in the theme provider.

I'm trying to get a form working, this is the implementation

```
      <VMContext
        vm="NewTrialForm"
        onStateChange={state => {
          console.log(JSON.stringify(state));
          if (state.RequestId !== "") {
            this.props.getRequestID(state.RequestId);
          }
        }}
      >
        <Form>
          <TextField
            id="FirstName"
            label="FirstName"
            required
            autoFocus
            fullWidth
            inputComponent={MuiTextField}
          />
        </Form>
      </VMContext>
```

however this throws an error in the console 

> dotnetify-elements.js:655 Uncaught TypeError: Cannot read property 'Container' of undefined
>     at dotnetify-elements.js:655
>     at styled-components.browser.es.js:95
>     at Array.reduce (<anonymous>)
>     at flatten (styled-components.browser.es.js:73)
>     at ComponentStyle.generateAndInjectStyles (styled-components.browser.es.js:2048)
>     at StyledComponent.generateAndInjectStyles (styled-components.browser.es.js:1739)
>     at StyledComponent.componentWillMount (styled-components.browser.es.js:1780)
>     at callComponentWillMount (react-dom.development.js:13025)
>     at mountClassInstance (react-dom.development.js:13123)
>     at updateClassComponent (react-dom.development.js:14854)
>     at beginWork (react-dom.development.js:15716)
>     at performUnitOfWork (react-dom.development.js:18750)
>     at workLoop (react-dom.development.js:18791)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:147)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:196)
>     at invokeGuardedCallback (react-dom.development.js:250)
>     at replayUnitOfWork (react-dom.development.js:17998)
>     at renderRoot (react-dom.development.js:18909)
>     at performWorkOnRoot (react-dom.development.js:19812)
>     at performWork (react-dom.development.js:19722)
>     at performSyncWork (react-dom.development.js:19696)
>     at requestWork (react-dom.development.js:19551)
>     at scheduleWork (react-dom.development.js:19358)
>     at Object.enqueueSetState (react-dom.development.js:12789)
>     at t.push../node_modules/dotnetify-elements/node_modules/react/cjs/react.development.js.Component.setState (react.development.js:242)
>     at setState (dotnetify-elements.js:1465)
>     at dotnetifyVM.State (dotnetify-react.js:851)
>     at dotnetifyVM.$update (dotnetify-react.js:1057)
>     at Object._responseVM (dotnetify-react.js:394)
>     at dotnetify-react.js:319
>     at dotnetify-react.js:709
>     at Array.forEach (<anonymous>)
>     at Object.emit (dotnetify-react.js:708)
>     at HubConnection._dotnetifyHub2.default.client.response_VM (dotnetify-react.js:2160)
>     at HubConnection.js:544
>     at Array.forEach (<anonymous>)
>     at HubConnection.invokeClientMethod (HubConnection.js:543)
>     at HubConnection.processIncomingData (HubConnection.js:450)
>     at WebSocketTransport.HubConnection.connection.onreceive (HubConnection.js:165)
>     at WebSocket.webSocket.onmessage (WebSocketTransport.js:215)
> (anonymous) @ dotnetify-elements.js:655
> (anonymous) @ styled-components.browser.es.js:95
> flatten @ styled-components.browser.es.js:73
> generateAndInjectStyles @ styled-components.browser.es.js:2048
> generateAndInjectStyles @ styled-components.browser.es.js:1739
> componentWillMount @ styled-components.browser.es.js:1780
> callComponentWillMount @ react-dom.development.js:13025
> mountClassInstance @ react-dom.development.js:13123
> updateClassComponent @ react-dom.development.js:14854
> beginWork @ react-dom.development.js:15716
> performUnitOfWork @ react-dom.development.js:18750
> workLoop @ react-dom.development.js:18791
> callCallback @ react-dom.development.js:147
> invokeGuardedCallbackDev @ react-dom.development.js:196
> invokeGuardedCallback @ react-dom.development.js:250
> replayUnitOfWork @ react-dom.development.js:17998
> renderRoot @ react-dom.development.js:18909
> performWorkOnRoot @ react-dom.development.js:19812
> performWork @ react-dom.development.js:19722
> performSyncWork @ react-dom.development.js:19696
> requestWork @ react-dom.development.js:19551
> scheduleWork @ react-dom.development.js:19358
> enqueueSetState @ react-dom.development.js:12789
> push../node_modules/dotnetify-elements/node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:242
> setState @ dotnetify-elements.js:1465
> State @ dotnetify-react.js:851
> $update @ dotnetify-react.js:1057
> _responseVM @ dotnetify-react.js:394
> (anonymous) @ dotnetify-react.js:319
> (anonymous) @ dotnetify-react.js:709
> emit @ dotnetify-react.js:708
> _dotnetifyHub2.default.client.response_VM @ dotnetify-react.js:2160
> (anonymous) @ HubConnection.js:544
> HubConnection.invokeClientMethod @ HubConnection.js:543
> HubConnection.processIncomingData @ HubConnection.js:450
> HubConnection.connection.onreceive @ HubConnection.js:165
> webSocket.onmessage @ WebSocketTransport.js:215
> index.js:1452 The above error occurred in the <Field__Container> component:
>     in Field__Container
>     in t
>     in t (at TrialFormContainer/index.js:37)
>     in form
>     in t (at TrialFormContainer/index.js:36)
>     in t (at TrialFormContainer/index.js:27)
>     in TrialFormContainer (at Create.js:14)
>     in Create (created by Route)
>     in Route (created by withRouter(Create))
>     in withRouter(Create) (at page/index.js:20)
>     in StoreProvider (at page/index.js:15)
>     in ErrorBoundary (at Layout/index.js:53)
>     in div (at Layout/index.js:52)
>     in div (at Layout/index.js:51)
>     in Transition (created by Fade)
>     in Fade (created by WithTheme(Fade))
>     in WithTheme(Fade) (at Layout/index.js:50)
>     in div (at Layout/index.js:23)
>     in Layout (created by WithStyles(Layout))
>     in WithStyles(Layout) (at page/index.js:14)
>     in Page (at app/index.js:36)
>     in Suspense (at app/index.js:35)
>     in CssBaseline (created by WithStyles(CssBaseline))
>     in WithStyles(CssBaseline) (at app/index.js:34)
>     in MuiThemeProviderOld (at app/index.js:33)
>     in Router (created by BrowserRouter)
>     in BrowserRouter (at app/index.js:32)
>     in ErrorBoundary (at app/index.js:31)
>     in Unknown (at src/index.js:11)
> 
> React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.

So then i have to add a `<Panel>` in, which also throws an error if it's not nested in a `<Theme>` component.

After that, the form works fine and renders, but then the styles that have been defined for the label/error message are no longer used and it seems to pull the styles from the `withTheme` HOC.

Is it possible to ignore the styles? Or would it be possible to use the native Material UI attributes such as error/helperText?

Thanks
Tom

**Comment by dsuryd** [comment]
Try this:
```jsx
const theme = createMuiTheme({ ...})
...
export default withTheme(_ => (
   <MuiThemeProvider theme={theme}>
      <YourForm />
   </MuiThemeProvider>
));
```

**Comment by tjackadams** [comment]
@dsuryd thanks for your response, but its still the same unfortunately.

Looking at this a bit further, it does seem to pass the correct styles down for the material ui TextField component. However, it just appears to be the Label and HelperText.

Here is the generated HTML for the dotnetify TextField


```
<div class="Field__Container-gqSdms bUfMrz">
   <div class="Field__LabelContainer-dfUkj gzKgXM">
      <div class="Label__LabelContainer-gsSpeQ eerIAr">First Name</div>
   </div>
   <div class="Field__InputContainer-czcsEe jHqcmA">
      <div class="MuiFormControl-root-1 MuiFormControl-fullWidth-4">
         <div class="MuiInputBase-root-18 MuiInput-root-5 MuiInput-underline-9 MuiInputBase-fullWidth-27 MuiInput-fullWidth-12 MuiInputBase-formControl-19 MuiInput-formControl-6"><input aria-invalid="false" class="MuiInputBase-input-28 MuiInput-input-13" id="FirstName" required="" type="text" value=""></div>
      </div>
   </div>
   <div class="Field__ValidationMessageContainer-cArDNs iLoghW"></div>
</div>
```

Here is the HTML output of a a material UI TextField component 

```
<div class="Panel__ChildContainer-gSbRTa kfyxih">
   <div class="MuiFormControl-root-1 MuiFormControl-fullWidth-4">
      <label class="MuiFormLabel-root-46 MuiFormLabel-required-51 MuiInputLabel-required-39 MuiInputLabel-root-35 MuiInputLabel-formControl-40 MuiInputLabel-animated-43" data-shrink="false" for="FirstName2">First Name 2<span class="MuiFormLabel-asterisk-52"> *</span></label>
      <div class="MuiInputBase-root-18 MuiInput-root-5 MuiInput-underline-9 MuiInputBase-fullWidth-27 MuiInput-fullWidth-12 MuiInputBase-formControl-19 MuiInput-formControl-6"><input aria-invalid="false" class="MuiInputBase-input-28 MuiInput-input-13" id="FirstName2" required="" type="text" value=""></div>
   </div>
</div>
```

i'm guessing there is an issue mapping the props between the two components?

Also, i receive this error in the console when using `inputComponent={MuiTextField}`

> Warning: React does not recognize the `inputComponent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputcomponent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     in div (created by FormControl)
>     in FormControl (created by WithStyles(FormControl))
>     in WithStyles(FormControl) (created by TextField)
>     in TextField
>     in Unknown
>     in div
>     in Field__InputContainer
>     in div
>     in Field__Container
>     in t
>     in t (at TrialFormContainer/index.js:38)
>     in div
>     in Panel__Container
>     in t (at TrialFormContainer/index.js:37)
>     in form
>     in t (at TrialFormContainer/index.js:36)
>     in t (at TrialFormContainer/index.js:27)
>     in TrialFormContainer (at app/index.js:54)
>     in Suspense (at app/index.js:53)
>     in ErrorBoundary (at app/index.js:52)
>     in CssBaseline (created by WithStyles(CssBaseline))
>     in WithStyles(CssBaseline) (at app/index.js:51)
>     in MuiThemeProviderOld (at app/index.js:50)
>     in Unknown
>     in ThemeProvider
>     in t
>     in n (at src/index.js:11)
>

**Comment by dsuryd** [comment]
The problem with the `label` is due to the fact that it's already reserved for the `TextField` itself, and therefore won't be passed down to the inner MUI component.  But both this and the warning can be worked around by using an HOC:

```jsx
const muiTextFieldFactory = args => ({ inputComponent, ...props }) => <MuiTextField {...props} {...args} />;
...
<TextField id="Name" inputComponent={muiTextFieldFactory({ label: 'Name' })} />
```

**Comment by tjackadams** [comment]
@dsuryd thank you very much. Seems to be working fine for the label now, the errors are still pulling the dotnetify styles through but i think i can get around that.

Would there be anyway to do a similar thing for a button? I've tried to apply the same approach but it doesn't seem the `Button` component takes an `inputComponent` prop?

**Comment by dsuryd** [comment]
Buttons use `buttonComponent`, not `inputComponent`.  Check the customize tab  for a particular element in the website.

**Comment by tjackadams** [comment]
apologies for that! the `buttonComponent` works fine. Thank you for your help.

**Comment by RobertTheGrey** [comment]
This thread has helped me a lot in getting MUI working with the latest dotnetify Elements. Very smooth once you know how, but tricky to figure out without docs around the theming section. Once I figure out how it all works I'll try and contribute back to the docs on this @dsuryd. In the meantime, I'm also seeing a ton of warnings that @tjackadams was also getting: `Warning: React does not recognize the inputComponent prop on a DOM element` or `Warning: React does not recognize the `fullId` prop on a DOM element` - I'm guessing the latter one is something to do with how dotnetify Elements tracks components?

Any thoughts on the best way to approach this as they fill up the console and mask other issues.

**Comment by tjackadams** [comment]
@RobertTheGrey what type of component are you trying to render? I mainly got these errors with the button component because i was not using the correct props. Here is an example of the button factory method i ended up with. The fullId prop is pulled out before passing the rest of the props to the mui component.

```
const buttonFactory = args => ({ buttonComponent, ...props }) => {
  const { fullId, plainText, ...rest } = props;
  return <Button {...rest} {...args} />;
};
```

which is then rendered like so 

```
            <Button
              id="ActivateTrial"
              submit
              buttonComponent={buttonFactory()}
              variant="contained"
              color="primary"
            >
              Active Free Trial
            </Button>
```

**Comment by RobertTheGrey** [comment]
@tjackadams thanks for the pointer! Agreed, if I use a factory I can pull out the unexpected `props`, I was just trying to use it in place without a factory for components that didn't explicitly need it, for example:
```
import { Button as MuiButton, TextField as MuiTextField } from "@material-ui/core";
import { Button, TextField } from "dotnetify-elements";
.....
<TextField
   id="Password"
   label="Password"
   fullWidth
   type="password"
   value={password}
   onChange={value => this.setState({ password: value })}
   inputComponent={MuiTextField}
/>
<Button
    variant="contained"
    color="primary"
    buttonComponent={MuiButton}
    onClick={handleLogin}
>
    Login
</Button>
```
So I guess the strategy then is to create a bunch of factories that remove unnessecary props and import them into every component right? I was hoping for something with a little less boilerplate given the bootstrap theme seems to *Just Work* out the box.

Happy to be steered in the right direction if I'm missing something?
Thanks again!

**Comment by dsuryd** [comment]
If your application exclusively uses Material-UI, here's what I would do:  create a file to import the elements which the app will use, assign the `componentTypes` properties with MUI component adaptors, and import this file from the root app.

For example:
```jsx
import { Button } from 'dotnetify-elements/components/Button';
import { TextField } from 'dotnetify-elements/components/TextField';

import MuiTextField from '@material-ui/core/TextField';
import MuiButton from '@material-ui/core/Button';

const MuiTextFieldAdaptor = ({ muiLabel, ...props }) => <MuiTextField label={muiLabel} {...props} />;

const MuiButtonAdaptor = ({ fullId, plainText, primary, secondary, positive, negative, cancel, ...props }) => {
   const color = primary || positive ? 'primary' : secondary || negative ? 'secondary' : null;
   return <MuiButton id={fullId} color={color} {...props} />;
};

Button.componentTypes.ButtonComponent = MuiButtonAdaptor;
TextField.componentTypes.InputComponent = MuiTextFieldAdaptor;
```

The rest of your application then won't be needing to import material-UI components.

**Comment by RobertTheGrey** [comment]
That's a fantastic strategy @dsuryd - I'll find out if the project is exclusively MUI and implement this if so. Still, I think it's worth documenting both approaches, so I'll send a PR to the docs when I've had a play and am confident in the approach. Thanks again for a great, flexible set of frameworks here!
