### ISSUE TITLE
Multiple messages for a validation

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#34]
Is it possible to produce different error messages by an on server validation for a field?
I'm working on an app that that shares app logic between a webapp based on dontnetify and a webapi.
Both share validation, so my application layer  provides methods for validating entities when are received on server side.
It checks foreign keys integrity and other business rules. So, a validation of an entity can return multiple errors, that should be shown after an unsuccessful server side validation after user submit.
I've guessed that this is not possible if previously I didn't define a  With...Validation() for each property of those that can show an error message.
Is it possible to have a With...Validation() method that only provides the error properties to communicate from server the errors related to a field but do not force to do any validation on  client or server side when the field changes?
Is it possible to let the server side to provide the message at validation time, instead of having to provide all the possible errors when the form is loaded?
Is it possible to have a kind of generic method WithServerValidationOnSubmit()  for all the form that allows to set errors for different fields?
Finally, if I use .WithServerValidation() for a field is it possible to provide also differente messages at validation time?

**Comment by dsuryd** [comment]
`With...Validation` is intended as field-level UI validation - to test user input of individual fields to allow the user to correct superficial errors before he/she commits it.    

What you're indicating is a validation of input as a whole against business invariants.  In this case, I would recommend that you don't use `With...Validation` for this purpose, but instead validate the form data in your view model when it's received by the Submit button property, and send back to the client the aggregated validation error message and display it in an Alert element placed before or after the Form element, like in the [Basic Form Demo](http://dotnetify.net/elements/form/demo).
