### ISSUE TITLE
Allow to declare DataGrid Column as Editable

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#37]
Can `editable` and `editor` properties be used with GridColumn Element for harnessing those react-data-grid properties for editing data of a selected cell.
Adding those properties doesn't seem to have any effect on the underlying react-data-grid.
Is it on purpose for any reason?

Thank you

**Comment by dsuryd** [comment]
Adding editable data grid that seamlessly update the backing data model on the server will be a significant effort that require thoughtful design, so it wont' be in the initial release version of this library.  It can be considered for future work if there's much demand.

**Comment by jersiovic** [comment]
So, what's your recommendation for working with editable data grids in a form with what dotnetify currently provides?
Maybe, is it to use my own element based of your DataGrid.js but specifically customize just for my use case with exactly the columns I need for my use case? Maybe harnessing BaseVM CRUD API http://dotnetify.net/core/api/crud ? Would this reduce considerabily the amount of effort?

**Comment by jersiovic** [comment]
Can you reopen this issue to allow others to show their interest on an editable DataGrid element for meassuring  its demand?

**Comment by dsuryd** [comment]
This would be non-trivial if this involves automatically updating the backing model, but if the responsibility of this element is limited to just communicate changed data to the view model, then this would probably be less of an effort.

**Comment by dsuryd** [comment]
Just published a version that will allow editing of data grid cells, and also allow passing of react-data-grid editors.  See updated [documentation](http://www.dotnetify.net/elements/display/datagrid) for details.
