### ISSUE TITLE
Bundle Size Optimizations

### ISSUE THREAD

**Issue by tjackadams** [dsuryd/dotNetify-Elements#38]
I wanted to open this issue as a place to discuss the current bundle size and offer any solutions for reducing this.

with a basic react application and webpack set to production, currently i'm getting a bundle size of about 1.7mb which is huge!

Here is the react application for reference

```
import React from "react";
import ReactDOM from "react-dom";

import Element from "dotnetify-elements";

const Index = () => {
  return (
    <div>
      <Element id="1234" />
    </div>
  );
};

ReactDOM.render(<Index />, document.getElementById("app"));
```

After using the webpack-bundle-analyzer webpack plugin, there are a few areas that catch my eye but maybe some other suggestions could be added.

![image](https://user-images.githubusercontent.com/2307314/51075093-ee3a4f80-167e-11e9-9a6b-747cbe14d6c7.png)

So here are a few

- [ ] React is bundled with the library.
- [ ] All the moment locales are bundled. 
- [ ] react-data-grid is huge.

and i'm sure there are other issues that people might spot. I'll try and get a pr raised this weekend to resolve the first item, but it might require a bit more thought to tackle the others.

Anyway, its a great library and i just want to help any way i can.

**Comment by dsuryd** [comment]
Thank you!  I agree it's an issue, but which I was fully aware of when I first published this library (although I'm surprised React is still part of the bundle, as it's already marked as 'external' in the webpack config).  

I chose to initially bundle everything in one file for simplicity to people who want to try it out (i.e. only a single import).   Ideally I'm hoping the webpack tree-shaking has progressed enough to just trim out unreferenced dependencies to keep the final bundle size small, but if this isn't possible yet, the next step, in addition to the single bundle, will be to offer separate file imports for each component.

**Comment by dsuryd** [comment]
The latest version now provides individual component files to address the above issues.   The remaining one to figure out is the moment locales.

**Comment by dsuryd** [comment]
Solved the moment locale issue by utilizing`webpack.ContextReplacementPlugin`.  Details in the [documentation](http://www.dotnetify.net/elements/getstarted).

**Comment by tjackadams** [comment]
Thanks! :thumbsup:
