### ISSUE TITLE
TypeScript Definitions?

### ISSUE THREAD

**Issue by debuggingmyhead** [dsuryd/dotNetify-Elements#4]
Hello,

Awesome work on the library! I was just curious, though, if you had any plans to create TypeScript definitions for dotNetify-elements?

**Comment by dsuryd** [comment]
Not in the near future; but I would love to see others that regularly work with Typescript to pick it up.

**Comment by debuggingmyhead** [comment]
Sounds good. I may end up making them myself, in which case I will share them.
