### ISSUE TITLE
[Elements] I'm not able to execute a simple action when a button inside a Form is clicked

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#41]
This samples works properly for me without problems. However when I try to add a button that executes an action in the viewmodel I don't manage to get it done:

```
[React]
...
<Button label="Next" id="Next" show={!edit} />
...

[VM contructor in C# Alternative 1]
...
AddProperty<object>("Next")
                .Subscribe(_ => LoadFormWithNextItemAsync().GetAwaiter().GetResult());
...                

[VM contructor in C# Alternative 2]
...
AddProperty<object>("Next")
                .SubscribedBy(AddProperty<bool>("NextSuccess"), _ => LoadFormWithNextItemAsync().GetAwaiter().GetResult());
...
```
For anyone of these two alternatives it does nothing. I use dotnetify.debug=true in React Code but after the click there is not any tranmision of data. I set a breakpoint int the body of the lambda but it never stops there so no calls to `LoadFormWithNextItemAsync().GetAwaiter().GetResult()`

Any idea of what am I doing wrong?

**Comment by dsuryd** [comment]
Do you see debug output that data is being sent to the server when the
button is clicked?
