### ISSUE TITLE
Clarify if Elements uses websockets directly or through SignalR in the Readme.md

### ISSUE THREAD

**Issue by undecided2013** [dsuryd/dotNetify-Elements#43]
The readme.md says it uses websockets. DotNetify itself uses SignalR now (implicitly uses websockets). Does Elements use websockets directly or through the same dotNetify signalR pathway?

Thx

**Comment by dsuryd** [comment]
It's the latter.

**Comment by undecided2013** [comment]
Thanks Dicky, this stuff is amazing...
