### ISSUE TITLE
Is it possible to access the state set in a VMContext to fullfill an attribute of regular html tag?

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#7]
This works if you need to get a value from the state of the VMContext:
```
<VMContext vm="FamilyVM">
                <h1><Element id="VMTitle"></h1>
<VMContext vm="FamilyVM">
```
However what if you need to assing it to an attribute. This obviously doesn't work:
```
<VMContext vm="FamilyVM">
                <a href={Url}>My Link</a>
<VMContext vm="FamilyVM">
``
Is there a way for doing it?

**Comment by dsuryd** [comment]
It's not documented yet, but VMContext exposes `onStateChange` property that allows you to access the state for this very need.

**Comment by jersiovic** [comment]
Cool, thank you!
