### ISSUE TITLE
Show attribute on texfields doesn't work as expected

### ISSUE THREAD

**Issue by jersiovic** [dsuryd/dotNetify-Elements#9]
This textfield is not hidden when it should be hidden. However buttons that use same function to set the show attribute works properly.
![image](https://user-images.githubusercontent.com/4950766/45848205-e3555b00-bd2d-11e8-94af-4379c2eaf73f.png)
If I change it per a button then the button is hidden properly
![image](https://user-images.githubusercontent.com/4950766/45848258-14ce2680-bd2e-11e8-854e-489eba1895b5.png)

**Comment by dsuryd** [comment]
The `show` attribute is only supported by Button at least in the current version.  I have reservation to include it in other elements, because the conditional React syntax has better rendering efficiency:
```jsx
<Panel>
   {!edit()  && <Button label="Go to" />}
 </Panel>
```

**Comment by jersiovic** [comment]
thank you

**Comment by jersiovic** [comment]
to make things more predecible, why don't you remove it also from buttons?

**Comment by dsuryd** [comment]
Good point. I will consider it.  Thanks!
